---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: oddos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system/etc
        destination: /etc
      - source: system/usr
        destination: /usr

  - type: dnf
    install:
      packages:
        - ardour9
        - kdenlive

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
          - org.musescore.MuseScore
          - org.localsend.localsend_app
          - org.jjazzlab.JJazzLab
          - org.gnome.Boxes.Extension.OsinfoDb
          - md.obsidian.Obsidian
          - io.ente.auth
          - com.obsproject.Studio
          - io.ente.photos

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
